name: Lint and Build Next.js Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Lint the code
        run: cd peer-assessment-app && npm run lint

      - name: Type Check
        run: cd peer-assessment-app && npm run type-check

      - name: Check Code Formatting with Prettier
        run: cd peer-assessment-app && npm run format:check

      - name: Build the project
        run: npm run build

