name: Lint, Build, and Test Next.js Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password123
          MYSQL_DATABASE: SOEN341
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'

      - name: Install dependencies
        working-directory: peer-assessment-app
        run: npm install

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: poetry install

      - name: Lint the code
        working-directory: peer-assessment-app
        run: npm run lint

      - name: Type Check
        working-directory: peer-assessment-app
        run: npm run type-check

      - name: Format Code with Prettier
        working-directory: peer-assessment-app
        run: npm run format:check || echo "Prettier found issues, but continuing without failing the job."

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      - name: Run database migrations
        working-directory: peer-assessment-app
        env:
          MYSQL_PWD: password123
        run: |
          mysql -h 127.0.0.1 -u root SOEN341 < ../MySQL\ scripts/database.sql
          mysql -h 127.0.0.1 -u root SOEN341 < ../MySQL\ scripts/db_population.sql

     # Backend Tests

      - name: Build the project
        working-directory: peer-assessment-app
        run: npm run build

      - name: Run backend tests
        working-directory: peer-assessment-app
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: password123
          DB_DATABASE: SOEN341
        run: pytest .\tests\test_register_api.py 

      # - name: Run frontend tests
      #   working-directory: peer-assessment-app
      #   env:
      #     DB_HOST: 127.0.0.1
      #     DB_PORT: 3306
      #     DB_USER: root
      #     DB_PASSWORD: password123
      #     DB_DATABASE: SOEN341
      #   run: npm run test:frontend

